<?php

namespace AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    public function update($contact) {
        $this->_em->persist($contact);
        $this->_em->flush($contact);
    }

    public function deleteByOrganizer($organizer) {
        $query = $this
                ->createQueryBuilder('c')
                ->delete()
                ->where('c.organizer = (:organizer)')
                ->setParameter('organizer', $organizer)
                ->getQuery();

        return $query->getResult();
    }
}
