<?php

namespace AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrganizerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizerRepository extends EntityRepository
{
    public function findAllActive() {
        $query = $this
                ->createQueryBuilder('o')
                ->select('o')
                ->where('o.isActive = true')
                ->getQuery();

        return $query->getResult();
    }

    public function update($organizer) {
        $this->_em->persist($organizer);
        $this->_em->flush($organizer);
    }

    public function delete($organizer) {
        $this->_em->remove($organizer);
        $this->_em->flush();
    }
}
