parameters:
#    shopper_shop.example.class: Shopper\ShopBundle\Example

services:
#    shopper_shop.example:
#        class: %shopper_shop.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
